### ISSUE TITLE
Multiple Inverters

### ISSUE THREAD

**Issue by Genemills** [dekinet/MMM-Soliscloud#2]
I have a total of 66 panels running on 3 inverters. Any plans to be able to combine inverters for a total?

**Comment by dekinet** [comment]
hi, thanks for your interest in this project. Can't say I did have any plans to extend this... the module was created on request from another user as a port from another solar panel module I created (for a different product). The main issue is that I do not have access to any soliscloud inverters of my own to test changes.

Options are:
1. Do you have the skills to modify the code to support mutliple inverters? I'd be happy to review and merge any changes.
2. I could attempt to make changes without being able to test on a real system. This may or may not be successful, and would require your assistence to test the changes.
3. Maybe you could set up a temporary API key/token for me to access the API for your system. This is, I understand, a risk on your part and might not be something you're willing to do.
