### ISSUE TITLE
Screenshot and keywords

### ISSUE THREAD

**Issue by KristjanESPERANTO** [dekinet/MMM-Soliscloud#3]
In [the new module list](https://kristjanesperanto.github.io/MagicMirror-3rd-Party-Modules/) I am working on, a screenshot and tags are displayed for each module.

Would be nice if you could add a screenshot and keywords.

The keywords are read from the package.json. So far there are no keywords in the package.json of your module. It would be nice if you could add some. [Here you can see an example of a package.json with keywords.](https://github.com/jalibu/MMM-NINA/blob/04896f1ed9139059ea1b9d24ada4161d70e13030/package.json#L10)

This would be my suggestion:

```json
  "keywords": [
    "MagicMirror",
    "Soliscloud",
    "Solis",
    "solar"
  ],
```

**Comment by dekinet** [comment]
Hi @ragziesoft, would you be able to provide a screenshot of the working module as per request above from @KristjanESPERANTO ? Thanks.

**Comment by dekinet** [comment]
@KristjanESPERANTO I've added keywords, however I don't have access to a working system for a screenshot.

**Comment by KristjanESPERANTO** [comment]
@dekinet Okay, keywords are a step forward. Thanks! :tada: 

@decoorebp: Since you opened an issue today maybe you could provide a screenshot of the module. That would be awesome :smiley:

**Comment by decoorebp** [comment]
![image](https://github.com/user-attachments/assets/085658e0-e611-4a81-bf24-f7710cefc828)

here is a screenshot of the fields I use today. But there is more available

**Comment by CyberRagz** [comment]
Hi, I have not updated the module( that is if it has been updated recently). However I am attaching the screenshot of my current running module.Sent by telepathy On 19 Sep 2024, at 04:10, dekinet ***@***.***> wrote:﻿
Hi @Ragziesoft, would you be able to provide a screenshot of the working module as per request above from @KristjanESPERANTO ? Thanks.

**Comment by dekinet** [comment]
Thanks @Ragziesoft .... nothing was attached that I can see though?

**Comment by CyberRagz** [comment]
Sent by telepathy On 20 Sep 2024, at 08:13, dekinet ***@***.***> wrote:﻿
Thanks @Ragziesoft .... nothing was attached that I can see though?

**Comment by CyberRagz** [comment]
Oh sorry for that i guess direct upload from email did not work . I will drop it here
![thumbnail](https://github.com/user-attachments/assets/79bb9d11-247a-4d64-a748-5017575cb5ac)

**Comment by KristjanESPERANTO** [comment]
@decoorebp and @Ragziesoft: Thanks for the screenshots! I've created PR #6 to implement them :slightly_smiling_face:

**Comment by KristjanESPERANTO** [comment]
I'm closing this issue. PR has been accepted and the module looks perfect now in the new module list :slightly_smiling_face: Thanks!
