### ISSUE TITLE
Sorry for the intrusion!

### ISSUE THREAD

**Issue by waylonis** [dekinet/MMM-Soliscloud#4]
Hi,

Github is lame and doesn't allow users to send messages to each other, so I'm sorry in advance to misuse Issues as a message board.

I have a registered domain `nekotech.com` that I've had since 1996. I tried to register the organization with GitHub but was denied because there was already one. However, it doesn't look like this "nekotech" that is associated with your user account is being actively used:

https://github.com/nekotech/react-course-2-expensify-app

If you wouldn't mind, could you assist me in transferring ownership of the organization to me if it's no longer useful to you?

Thanks!
Dan

**Comment by dekinet** [comment]
Hi Dan, I _would_ be using the account if GitHub hadn't locked me out. There's several private repositories in there I want to access. Unfortunately when I changed phones, the nekotech authenticator account didn't transfer to the new phone. None of the recovery codes I have work for some reason and GitHub support have refused to provide me access. Without being able to get into the account myself, I doubt there's anything I can do to facilitate transferring ownership. 
Sorry,
Matt

**Comment by waylonis** [comment]
Hi Matt,

Thanks so much for filling me in on the details! Really amazing that GitHub isn't helpful with cleaning up stuff that's no longer accessible. It's truly abandoned!

One last obscure question, how'd you come up with Nekotech? I was taking Japanese when I grabbed the domain back in 1994. Neko means cat (which I had two of) and tech was just me being nerdy 😀 

Dan
-----------------------------------------
Dan Waylonis | gmail.com
650.793.2957

**Comment by dekinet** [comment]
In case you don't check linkedin much, I've sent a connection request. It's more private than this mechanism.
